#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r constant/polyMesh_orig constant/polyMesh
cp system/fluid/snappyHexMeshDict system/snappyHexMeshDict
runApplication -s fluid.txt blockMesh
runApplication -s fluid.txt snappyHexMesh -overwrite
mv -f constant/polyMesh constant/fluid/
runApplication -s fluid.txt createPatch -region fluid -overwrite

cp -r constant/polyMesh_orig constant/polyMesh
cp system/solid/snappyHexMeshDict system/snappyHexMeshDict
runApplication -s solid.txt blockMesh
runApplication -s solid.txt snappyHexMesh -overwrite
mv -f constant/polyMesh constant/solid
runApplication -s solid.txt createPatch -region solid -overwrite

